import * as userActions from './UserActions';
import * as loginActions from './LoginActions';
import * as registerActions from './RegisterActions';
import * as serviceActions from './ServiceActions';
import * as stylerActions from './StylerActions';
import * as appointmentActions from './AppointmentActions';
import * as mapActions from './MapActions';
import * as contactActions from './ContactAction';

export const InitializeApp = userActions.InitializeApp;
export const doLogin = loginActions.doLogin;
export const logout = userActions.logout;
export const doRegister = registerActions.doRegister;
export const doSocialRegister = registerActions.doSocialRegister;
export const verifyAccount = userActions.verify;
export const verifySocialMediaLogin = loginActions.verifySocialMediaLogin;
export const getCurrentUser = userActions.loggedInUser;
export const fetchUsers = userActions.fetchUsers;
export const addService = serviceActions.addService;
export const listService = serviceActions.listService;
export const addStyler = stylerActions.addStyler;
export const listStylers = stylerActions.listStylers;
export const sortStylersService = stylerActions.sortStylersService;
export const getServiceStylers = stylerActions.getServiceStylers;
export const updateSelectedService = stylerActions.updateSelectedService;
export const updateSelectedOption = stylerActions.updateSelectedOption;
export const updateDate = appointmentActions.updateDate;
export const updateLocation = appointmentActions.updateLocation;
export const saveAppointment = appointmentActions.saveAppointment;
export const listAppointments = appointmentActions.listAppointments;
export const listStylerRequests = appointmentActions.listStylerRequests;
export const listStylerAppointments = appointmentActions.listStylerAppointments;
export const completeService = appointmentActions.completeService;
export const updateStylerService = stylerActions.updateStylerService;
export const removeStylerService = stylerActions.removeStylerService;
export const updateStyler = stylerActions.updateStyler;
export const checkStylerRegStatus = stylerActions.checkStylerRegStatus;
export const acceptAppointment = appointmentActions.acceptAppointment;
export const updateAppointmentStatus = appointmentActions.updateAppointmentStatus;
export const getCurrentLocation = mapActions.getCurrentLocation;
export const getInputData = mapActions.getInputData;
export const clearInputData = mapActions.clearInputData;
export const getAddressPredictions = mapActions.getAddressPredictions;
export const getSelectedAddress = mapActions.getSelectedAddress;
export const getStats = stylerActions.getStats;
export const contact = contactActions.contact;
export const updateStylerCurrentLocation = mapActions.updateStylerCurrentLocation;
export const updateUserStylerLocation = mapActions.updateUserStylerLocation;
export const updateProfile = userActions.updateProfile;
export const updateOneSignal = userActions.updateOneSignal;
export const listStylerServices = stylerActions.listStylerServices;
export const getSubServices = serviceActions.getSubServices;
export const servicePrice = stylerActions.servicePrice;
export const fetchUser = userActions.fetchUser;
export const filterService = serviceActions.filterService;
export const resetFilter = serviceActions.resetFilter;
export const initTransaction = appointmentActions.initTransaction;
export const fetchCards = userActions.fetchCards;
export const completeTransaction = appointmentActions.completeTransaction;
export const chargeAuthorization = appointmentActions.chargeAuthorization;
export const addStylerData = appointmentActions.addStylerData;
export const addRating = appointmentActions.addRating;
export const updateAvatar = stylerActions.updateAvatar;
export const changePassword = userActions.changePassword;
export const sendConfirmationCode = userActions.sendConfirmationCode;
export const confirmPasswordChange = userActions.confirmPasswordChange;
export const removeID = userActions.removeID;